add c1 migration scirpt (#17)
trendmicro/cloudone-community pull request #21
Opened 2022-06-23 03:24 UTC by felipecosta09

## Cloud One Service

[ ] **Common**

[X] **Workload Security**

[ ] **Application Security**

[ ] **Network Security**

[ ] **File Storage Security**

[ ] **Container Security**

[ ] **Conformity**

[ ] **Open Source Security**

## Proposed Changes
added c1 migration script to SA repo

2022-06-23 03:33 UTC, felipecosta09 commented
Code Linter and Code Scanning (Javascript) failed because is blocked by PR #18

2022-06-30 13:25 UTC, GeorgeDavis-TM reviewed
I would rename the project to apexone-to-cloudone-migration-script or something more self explanatory since we are looking the C1 to C1 region migrations too.

2022-06-30 14:58 UTC, felipecosta09 commented
> I would rename the project to apexone-to-cloudone-migration-script or something more self explanatory since we are looking the C1 to C1 region migrations too.

Make sense to me!

2022-06-30 15:53 UTC, felipecosta09 commented
@GeorgeDavis-TM Do you mind test this one? I know that you've used it before 😄

2022-11-04 17:22 UTC, JustinDPerkins commented
@jmlake569 :)

2022-11-04 17:24 UTC, jmlake569 commented
We need one more approval I think

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Justin Perkins ***@***.***>
Sent: Friday, November 4, 2022 1:22:48 PM
To: trendmicro/cloudone-community ***@***.***>
Cc: Jacob Lake (SE-US) ***@***.***>; Mention ***@***.***>
Subject: Re: [trendmicro/cloudone-community] feat: add c1 migration script (#17) (PR #21)



This message was sent from outside of Trend Micro. Please do not click links or open attachments unless you recognise the source of this email and know the content is safe.


@jmlake569<https://github.com/jmlake569> :)

—
Reply to this email directly, view it on GitHub<https://github.com/trendmicro/cloudone-community/pull/21#issuecomment-1303910858>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AI2KCADWB72AIIP24I6NQETWGVA6RANCNFSM5ZSYAJMQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

TREND MICRO EMAIL NOTICE

The information contained in this email and any attachments is confidential and may be subject to copyright or other intellectual property protection. If you are not the intended recipient, you are not authorized to use or disclose this information, and we request that you notify us by reply mail or telephone and delete the original message from your mail system.

For details about what personal information we collect and why, please see our Privacy Notice on our website at: Read privacy policy<http://www.trendmicro.com/privacy>

2023-01-23 21:07 UTC, JustinDPerkins requested changes

2023-01-23 21:07 UTC, JustinDPerkins commented on Workload-Security/Migration/ps-apexone-to-cloudone-migration-script/README.md
> +You can't break anything with this because it's already programmed to handle any situation on its own.
Remove line 20. other than that all good to me

2023-01-25 21:37 UTC, jmlake569 commented
Has this been resolved? Can we merge team?

2023-01-25 21:41 UTC, jmlake569 approved these changes

2023-01-25 21:42 UTC, jmlake569 commented
@JustinDPerkins I think this needs your blessing here

2023-01-25 22:36 UTC, JustinDPerkins approved these changes
LGTM

2023-01-25 23:30 UTC, merged