AWS Inspector Integration with C1WS
trendmicro/cloudone-community pull request #53
Opened 2022-10-19 14:34 UTC by wschadrach

## Cloud One Service
**select one or multiple if applicable**

[ ] **Common**

[ ] **Workload Security**

[ ] **Application Security**

[ ] **Network Security**

[ ] **File Storage Security**

[ ] **Container Security**

[ ] **Conformity**

[ ] **Open Source Security**

## Proposed Changes
  - New blah blah
  - Creates blah blah
  - Full details listed here.

2022-10-19 19:17 UTC, felipecosta09 requested changes
We need to have the code out of the zip file to run the Linter and security checks appropriately.

For the code to be used in the lambda, I think it would be best to have an s3 bucket and upload the code via cloud formation, but I'm open to other options as well, check the File Storage Plugins because they explore some deployment options there that might be valuable:

<https://github.com/trendmicro/cloudone-filestorage-plugins/blob/master/post-scan-actions/aws-python-promote-or-quarantine/other-installation-methods.md>

2022-10-24 17:20 UTC, JustinDPerkins commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/README.md
> +
I would add more details to the readme page. Ensure that all prereqs are listed before hand. Such as SES set up. Cloud One Api Key generation.

2022-10-24 17:21 UTC, JustinDPerkins commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/auto-assign-ips-rule.yaml
> +    ApiKey:
This needs to be secured. Not in plain-view

2022-10-24 17:25 UTC, JustinDPerkins requested changes

2022-10-24 17:25 UTC, JustinDPerkins commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/auto-assign-ips-rule.yaml
> +    CronSchedule:
Maybe include a default cron value of weekly reports.

2022-10-27 20:01 UTC, felipecosta09 commented
Hey @wschadrach any updates?

2022-10-28 05:17 UTC, wschadrach commented
> Hey @wschadrach any updates?

Yes, will repost the updated files soon

2022-11-02 21:30 UTC, wschadrach commented
> We need to have the code out of the zip file to run the Linter and security checks appropriately.
> 
> For the code to be used in the lambda, I think it would be best to have an s3 bucket and upload the code via cloud formation, but I'm open to other options as well, check the File Storage Plugins because they explore some deployment options there that might be valuable:
> 
> https://github.com/trendmicro/cloudone-filestorage-plugins/blob/master/post-scan-actions/aws-python-promote-or-quarantine/other-installation-methods.md

2022-11-02 21:30 UTC, closed without merging