C1 inspector integration
trendmicro/cloudone-community pull request #55
Opened 2022-11-02 21:32 UTC by wschadrach

## Cloud One Service
**select one or multiple if applicable**

[ ] **Common**

[ ] **Workload Security**

[ ] **Application Security**

[ ] **Network Security**

[ ] **File Storage Security**

[ ] **Container Security**

[ ] **Conformity**

[ ] **Open Source Security**

## Proposed Changes
  - New blah blah
  - Creates blah blah
  - Full details listed here.

2022-11-04 16:09 UTC, JustinDPerkins requested changes

2022-11-04 16:09 UTC, JustinDPerkins commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/auto-assign-ips-rule.yaml
> +  ApiKey:
The API key needs to be secured.

2022-11-04 16:51 UTC, JustinDPerkins commented
Could these two CFT's be combined into just one template or nested stack? The parameters between the two share a lot in common. Thoughts? @felipecosta09 @wschadrach

2022-11-04 17:23 UTC, JustinDPerkins commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/auto-assign-ips-rule.yaml
> +    Description: Email id to be used for sending report
Yeah i would use "Email address"

2022-11-04 17:26 UTC, JustinDPerkins commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/README.md
> +
Addin the README.md both how to create an api key and how to find out what their c1 region endpoint is

2022-11-04 17:28 UTC, JustinDPerkins commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/vulnerability_template.yaml
> +                # TODO: check for next token as max result is 50
could this be paginated to cover all instances?

2022-11-04 17:46 UTC, felipecosta09 commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/auto-assign-ips-rule.yaml
> +      - https://workload.sg-1.cloudone.trendmicro.com/api
agreed!

2022-11-08 16:45 UTC, felipecosta09 requested changes

2022-11-08 16:50 UTC, JustinDPerkins commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/c1-inspector-findings-protection.yaml
> +          apikey: !Ref ApiKey
Could you protect the API key with secrets manager or ssm param store.

2022-11-08 16:51 UTC, JustinDPerkins commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/c1-inspector-findings-protection.yaml
> +          apikey: !Ref ApiKey
Same here as before.

2022-11-10 21:38 UTC, felipecosta09 commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/c1-inspector-findings-protection.yaml
> +          - arn:aws:iam::aws:policy/AmazonSESFullAccess
I check here the managed policies so we have READONLY and Full Access so an inline policy here might be necessary to make sure we follow the "Least permissions" principle...

2022-11-10 21:44 UTC, felipecosta09 commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/c1-inspector-findings-protection.yaml
> +        S3Key: "python.zip"
Unless you can control under this cfn how the zip is being generated, I don't think is a good idea to hardcode it...

2022-11-10 21:58 UTC, felipecosta09 requested changes

2022-11-10 21:58 UTC, felipecosta09 commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/c1-inspector-findings-protection.yaml
> +                CHARSET = "UTF-8"
Just to keep the variable name consistent, all the variables are the following:

**python_var**

Why is using a different [convention](https://www.w3schools.com/python/gloss_python_variable_names.asp) for this one?

2022-11-10 21:58 UTC, felipecosta09 commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/c1-inspector-findings-protection.yaml
> +        - !Ref LambdaLayer1
Might be good to have a name for the layer that gives us an idea of what the layer actually does...

2022-11-22 21:09 UTC, felipecosta09 commented
Any updates @wschadrach ?

2022-11-22 21:42 UTC, wschadrach commented
> Any updates @wschadrach ?

I am done with all update just the securing of the api I have been working to solve

2022-12-15 15:56 UTC, wschadrach commented
> @wschadrach Any Updates?

I did a new commit before re:Invent I was just waiting on the team see if any one has any comment or just merge it if none.

2023-01-25 21:27 UTC, jmlake569 commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/README.md
> +[![Launch Stack](https://cdn.rawgit.com/buildkite/cloudformation-launch-stack-button-svg/master/launch-stack.svg)](https://console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=c1-inspecto
Are we still waiting on changes here? @raphabot @felipecosta09 @wschadrach

2023-02-08 20:13 UTC, JustinDPerkins requested changes

2023-02-08 20:13 UTC, JustinDPerkins commented on Workload-Security/Integration/aws-python-amazon-inspector-integration/c1-inspector-findings-protection.yaml
> +          Resource: "*"
Any IAM updates @wschadrach? Can you lock this down to a specific ses resource arn?

2023-02-13 21:59 UTC, JustinDPerkins submitted a review, later dismissed
LGTM

2023-03-23 16:11 UTC, JustinDPerkins approved these changes

2023-03-27 15:57 UTC, JustinDPerkins requested changes

2023-03-27 17:36 UTC, JustinDPerkins approved these changes
LGTM

2023-03-28 16:25 UTC, merged