feat: AWS Connectors Automation
trendmicro/cloudone-community pull request #76
Opened 2023-02-17 20:55 UTC by felipecosta09

## Cloud One Service

[X] **Common**

[ ] **Workload Security**

[ ] **Application Security**

[ ] **Network Security**

[ ] **File Storage Security**

[ ] **Container Security**

[ ] **Conformity**

[ ] **Open Source Security**

## Proposed Changes
  - Add project to automate connector creation

2023-03-08 19:40 UTC, JustinDPerkins requested changes

2023-03-08 19:40 UTC, JustinDPerkins commented on Common/Cloud-Account/aws-tf-connectors-automation/README.md
> + This automation is intended to streamline the process of setting up the Cloud One common connector for AWS, workload security connector for AWS and the AWS cloudtrail integration.
Could we link this to the C1 Doc page that explains the connector

2023-03-08 19:40 UTC, JustinDPerkins commented on Common/Cloud-Account/aws-tf-connectors-automation/README.md
> + This automation is intended to streamline the process of setting up the Cloud One common connector for AWS, workload security connector for AWS and the AWS cloudtrail integration.
if that exists of course

2023-03-08 19:40 UTC, JustinDPerkins commented on Common/Cloud-Account/aws-tf-connectors-automation/README.md
> +
Maybe make this a unique section like ###How to Verify

2023-03-08 19:40 UTC, JustinDPerkins commented on Common/Cloud-Account/aws-tf-connectors-automation/README.md
> +
Same here: how to remove

2023-03-08 19:40 UTC, JustinDPerkins commented on Common/Cloud-Account/aws-tf-connectors-automation/aws_connectors.tf
> +  c1-api-key = var.c1-api-key
If we require a c1 api key it should be noted in the readme with how to apply.

2023-03-08 19:40 UTC, JustinDPerkins commented on Common/Cloud-Account/aws-tf-connectors-automation/aws_connectors.tf
> +  c1-region = var.c1-region
Add to readme as well to obtain this info

2023-03-08 19:40 UTC, JustinDPerkins commented on Common/Cloud-Account/aws-tf-connectors-automation/connectors.tfvars
> +region = "us-east-1"
I would explain that this file needs to be updated with the unique values for deployment to work.

2023-05-05 19:33 UTC, atiradocc approved these changes

2023-06-02 19:18 UTC, closed without merging