feat: CloudFormation Stack for adding Common, WS and CloudTrail
trendmicro/cloudone-community pull request #82
Opened 2023-03-09 20:47 UTC by raphabot

## Cloud One Service
**select one or multiple if applicable**

[X] **Common**

[ ] **Workload Security**

[ ] **Application Security**

[ ] **Network Security**

[ ] **File Storage Security**

[ ] **Container Security**

[ ] **Conformity**

[ ] **Open Source Security**

[ ] **Other**

## Proposed Changes
  - CloudFormation Stack for adding Common, WS and CloudTrail

2023-03-09 23:30 UTC, JustinDPerkins reviewed
Code looks good. Any chance to get a readme to explain what this is/does?

2023-03-09 23:31 UTC, JustinDPerkins commented on Common/Cloud-Account/aws-cfn-cloud-account-connector/cloudone.template.yaml
> +        CloudOneOIDCProviderURL: "cloudaccounts.us-1.cloudone.trendmicro.com"
is us-1 the only OIDC url value?

2023-03-14 22:09 UTC, felipecosta09 requested changes
Another point is to consider is to use `arm64` lambda instead of `x86`, it's cheaper and in my experience, it has been delivering at least 20% more performance than x86 lambdas, since we have some custom resources here might be something to think about it...

2023-03-16 20:20 UTC, felipecosta09 approved these changes
LGTM

2023-03-16 21:14 UTC, merged